swagger: '2.0'
info:
  version: '1.0'
  title: Authendication API
  description: ''
host: testapi.instreamwealth.com
schemes:
  - https
basePath: /instreamapi
tags:
  - name: authendication-controller
    description: Authendication Controller
paths:
  /api/v1/auth/issue/token:
    post:
      tags:
        - authendication-controller
      summary: authenticateUser1
      operationId: authenticateUser1UsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JwtToken'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - APIKEY:
            - global
      deprecated: false
  /api/v1/auth/issue/token/client:
    post:
      tags:
        - authendication-controller
      summary: Used to get api access token
      operationId: authenticateUserUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: authenticationInfo
          description: authenticationInfo
          required: true
          schema:
            $ref: '#/definitions/AuthenticationRequestInfo'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/JwtToken'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization: []
        - APIKEY:
            - global
      deprecated: false
securityDefinitions:
  APIKEY:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AuthenticationRequestInfo:
    type: object
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
      grantType:
        type: string
      integrationId:
        type: integer
        format: int32
      integrationToken:
        type: string
      password:
        type: string
      userName:
        type: string
    title: AuthenticationRequestInfo
  JwtToken:
    type: object
    properties:
      accessToken:
        type: string
      accessTokenType:
        type: string
      expiryIn:
        type: integer
        format: int32
    title: JwtToken
